### ISSUE TITLE
Pressed on "Play" in Budgie Stream but there is no sound coming out of my speaker

### ISSUE THREAD

**Issue by zMasterSkill** [filahf/budgie-stream#16]
Hello,
i just downloaded Budgie Stream and i started a song on YouTube, selected the speaker in Budgie Stream and pressed on play. But there is no sound coming out of it. There is a playlist with 4 stream.mp3 files but its not playing.

**Comment by filahf** [comment]
Sounds like it's something wrong in the capture stage. If it's possible for you then I would recommend firing up the dev environment and have a look at console output. I'm planning to implement a way to see the current status and catch errors in the client. But in the meantime try the dev environment
